name: Emissions Test Reminder
options:
  bundleIdPrefix: com.shimondeitel.emissionremind
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Emissions Test Reminder:
    type: application
    platform: iOS
    sources:
      - path: Emissions Test Reminder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.emissionremind
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Emissions Test Reminder/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  Emissions Test ReminderTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Emissions Test ReminderTests
      - path: Emissions Test Reminder.storekit
    dependencies:
      - target: Emissions Test Reminder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.emissionremind.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  Emissions Test ReminderUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Emissions Test ReminderUITests
    dependencies:
      - target: Emissions Test Reminder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.emissionremind.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Emissions Test Reminder:
    build:
      targets:
        Emissions Test Reminder: all
        Emissions Test ReminderTests: [test]
        Emissions Test ReminderUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Emissions Test Reminder.storekit
    test:
      config: Debug
      storeKitConfiguration: Emissions Test Reminder.storekit
      targets:
        - Emissions Test ReminderTests
        - Emissions Test ReminderUITests
    archive:
      config: Release
